dotenv: .env

networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      fork: https://eth-mainnet.alchemyapi.io/v2/$ALCHEMY_KEY$FORK_BLOCK_NUMBER

autofetch_sources: true

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink@1.4.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink@1.4.0"
